apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prometheus
    repoURL: https://github.com/stockstatus/k8s_deploy_example.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
